services:
  postgresql:
    image: postgres
    container_name: "postgres-local"
    networks:
      - network-local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres@123
    volumes:
      - ./data:/var/lib/postgresql/data
      
networks:
  network-local:
    name: $NAME_NETWORK
    external: true      