services:
  jupyter-local:
    image: pyspark-local
    container_name: "jupyter-local"
    networks:
      - network-local
    user: root
    ports:
      - "8090:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: start.sh jupyter lab
    entrypoint: ./entrypoint.sh
networks:
  network-local:
    name: $NAME_NETWORK
    external: true
