services:
  mysql:
    image: mysql
    container_name: "mysql-local"
    networks:
      - network-local
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@123
    volumes:
      - ./data:/var/lib/mysql
      
networks:
  network-local:
    name: $NAME_NETWORK
    external: true      