services:
  minio:
    image: minio/minio
    container_name: "minio-local"
    networks:
      - network-local
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin@123
    volumes:
      - ./data:/data
      
networks:
  network-local:
    name: $NAME_NETWORK
    external: true      